use assistour;

SELECT DISTINCT HOTEL.NOM, HOTEL.ADRESSE
FROM HOTEL INNER JOIN HÉBERGER
ON HÉBERGER.IDHOTEL = HOTEL.IDHOTEL
WHERE HÉBERGER.IDDS = ( SELECT DSSINISTRE.IDDS
						FROM DSSINISTRE 
						WHERE DSSINISTRE.LaDATE LIKE "2022-05-20" );
						
SELECT DISTINCT SUM(NBNUITÉE)
FROM HOTEL INNER JOIN HÉBERGER
ON HÉBERGER.IDHOTEL = HOTEL.IDHOTEL
WHERE HÉBERGER.IDDS = ( SELECT DSSINISTRE.IDDS
						FROM DSSINISTRE 
						WHERE DSSINISTRE.LaDATE LIKE "2022-05-20" );
						
SELECT DISTINCT NUMORDRE , ETAPE.IDDS , HORAIRE , PRIX , VILLEDEPART , VILLEARRIVE
FROM ETAPE 
WHERE ETAPE.IDDS = ( SELECT DSSINISTRE.IDDS
					 FROM DSSINISTRE 
					 WHERE DSSINISTRE.LaDATE LIKE "2022-06-03" )
ORDER BY HORAIRE;

SELECT DISTINCT SUM(PRIX) , ETAPE.IDDS
FROM ETAPE 
WHERE ETAPE.IDDS = ( SELECT DSSINISTRE.IDDS
					 FROM DSSINISTRE 
					 WHERE DSSINISTRE.LaDATE LIKE "2022-06-03" )
						

